### ISSUE TITLE
Motorcykel 

### ISSUE THREAD

**Issue by Joel-Forsberg** [Maxhaell/Parkeringsgarage-#5]
Som Roger behöver jag smidigt få en parkering för att lätt få min motorcykelparkering.

 Kriterier
***

- Det ska åtminstone finnas en halv parkeringsplats, åt min motorcykeln

- Kunna registrera mig 

- Checka in och ut

- Se sin återstående tid

- Se priset för sin parkering

****

**Comment by AlexanderAberg** [comment]
1

**Comment by Maxhaell** [comment]
1
